### ISSUE TITLE
Error on publishing page with committee/board subpage

### ISSUE THREAD

**Issue by bcvandendool** [CosmosTUe/Cosmos#45]
When adding a committee or board subpage plugin to a page, and trying to publish it it given an integrity error regarding a duplicate key value violating a unique constraint.
<details><summary>error log</summary> <p>

Internal Server Error: /admin/cms/page/4/en/publish/
Traceback (most recent call last):
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "cosmos_cms_committeesubpagetitlepluginmodel_committee_id_key"
DETAIL:  Key (committee_id)=(1) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/bart/Projects/django-cms/cms/admin/pageadmin.py", line 1125, in publish_page
    all_published = page.publish(language)
  File "/home/bart/Projects/django-cms/cms/models/pagemodel.py", line 989, in publish
    self._copy_contents(public_page, language)
  File "/home/bart/Projects/django-cms/cms/models/pagemodel.py", line 635, in _copy_contents
    placeholder.copy_plugins(target_placeholder, language=language)
  File "/home/bart/Projects/django-cms/cms/models/placeholdermodel.py", line 577, in copy_plugins
    new_plugins = copy_plugins_to_placeholder(
  File "/home/bart/Projects/django-cms/cms/utils/plugins.py", line 217, in copy_plugins_to_placeholder
    new_plugin = CMSPlugin.add_root(instance=new_plugin)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/treebeard/mp_tree.py", line 625, in add_root
    return MP_AddRootHandler(cls, **kwargs).process()
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/treebeard/mp_tree.py", line 345, in process
    newobj.save()
  File "/home/bart/Projects/django-cms/cms/models/pluginmodel.py", line 271, in save
    super(CMSPlugin, self).save(*args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/bart/Projects/Cosmos/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "cosmos_cms_committeesubpagetitlepluginmodel_committee_id_key"
DETAIL:  Key (committee_id)=(1) already exists.

[19/Sep/2020 20:28:43] "POST /admin/cms/page/4/en/publish/ HTTP/1.1" 500 24514

</p></details>

**Comment by dasyad00** [comment]
@bcvandendool It's something involved with multiple databases support. Apparently the fix is running the following `python manage.py cms fix-tree`. Please close the issue if it fixes the problem.

**Comment by bcvandendool** [comment]
@dasyad00  Nope, doesnt solve the issue. I think it has sth to do with uniqueness as i am also unable to create a second plugin with the same board/committee. This also explains why it doesnt work for publishing as it creates a new plugin and then copies the content over.
